/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package stockinventorymanagement;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Anish
 */
public class exploreVendor extends javax.swing.JFrame {

    /** Creates new form searchVendor */
    public exploreVendor() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/images/logo.png")).getImage());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        btnempty = new javax.swing.JButton();
        btnsrch = new javax.swing.JButton();
        scrvendor = new javax.swing.JScrollPane();
        tblvendor = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        cbsrch = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        pnledit = new javax.swing.JPanel();
        txttin = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtgst = new javax.swing.JTextField();
        btnsave = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtmn = new javax.swing.JTextField();
        txtven = new javax.swing.JTextField();
        txtln = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtp1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtadd = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtp2 = new javax.swing.JTextField();
        txtcity = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnedit = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        sep = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        cbcrit = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Explore Vendor Master");
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(1200, 390));
        setResizable(false);
        setSize(new java.awt.Dimension(1200, 900));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 97, 1170, 10));

        btnempty.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnempty.setText("Empty Table");
        btnempty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnemptyActionPerformed(evt);
            }
        });
        getContentPane().add(btnempty, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 116, -1, -1));

        btnsrch.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnsrch.setText("Search in the database");
        btnsrch.setEnabled(false);
        btnsrch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsrchActionPerformed(evt);
            }
        });
        getContentPane().add(btnsrch, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 116, -1, -1));

        tblvendor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sr. No.", "Vendor Name", "Address", "City", "Mobile No.", "Landline No.", "Person (1)", "Person (2)", "E-mail", "Tin No.", "GST No."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblvendor.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        scrvendor.setViewportView(tblvendor);

        getContentPane().add(scrvendor, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 165, 1170, 270));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(62, 53, 171));
        jLabel2.setText("Search Field");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 16, -1, -1));

        cbsrch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Field", "vendorName", "address", "city", "mobileNo", "landlineNo", "person1", "person2", "email", "tinNo", "gstNo" }));
        cbsrch.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbsrchItemStateChanged(evt);
            }
        });
        cbsrch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbsrchActionPerformed(evt);
            }
        });
        getContentPane().add(cbsrch, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 56, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(62, 53, 171));
        jLabel3.setText("Criteria");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 16, -1, -1));

        pnledit.setBackground(new java.awt.Color(141, 230, 247));
        pnledit.setBorder(javax.swing.BorderFactory.createTitledBorder("Edit Vendor Master"));

        txttin.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(62, 53, 171));
        jLabel6.setText("Person (1) :");

        txtgst.setEnabled(false);

        btnsave.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnsave.setText("Save Changes");
        btnsave.setEnabled(false);
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(62, 53, 171));
        jLabel7.setText("Person (2) :");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(62, 53, 171));
        jLabel1.setText("Vendor Name :");

        txtmn.setEnabled(false);

        txtven.setEnabled(false);
        txtven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvenActionPerformed(evt);
            }
        });

        txtln.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(62, 53, 171));
        jLabel4.setText("Address :");

        txtp1.setEnabled(false);

        txtadd.setColumns(20);
        txtadd.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtadd.setLineWrap(true);
        txtadd.setRows(5);
        txtadd.setWrapStyleWord(true);
        txtadd.setEnabled(false);
        jScrollPane1.setViewportView(txtadd);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(62, 53, 171));
        jLabel8.setText("E-mail :");

        txtemail.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(62, 53, 171));
        jLabel5.setText("City :");

        txtp2.setEnabled(false);

        txtcity.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(62, 53, 171));
        jLabel9.setText("Tin No. :");

        btnedit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnedit.setText("Edit Details");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(62, 53, 171));
        jLabel10.setText("Mobile No. :");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(62, 53, 171));
        jLabel11.setText("GST No. :");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(62, 53, 171));
        jLabel12.setText("Landline No. :");

        javax.swing.GroupLayout pnleditLayout = new javax.swing.GroupLayout(pnledit);
        pnledit.setLayout(pnleditLayout);
        pnleditLayout.setHorizontalGroup(
            pnleditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnleditLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnleditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnleditLayout.createSequentialGroup()
                        .addGroup(pnleditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(btnedit, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnleditLayout.createSequentialGroup()
                        .addGroup(pnleditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel1)
                            .addComponent(jLabel12)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(pnleditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnleditLayout.createSequentialGroup()
                                .addGroup(pnleditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtmn, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                                    .addComponent(txtcity)
                                    .addComponent(txtln))
                                .addGap(50, 50, 50)
                                .addGroup(pnleditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel11)))
                            .addGroup(pnleditLayout.createSequentialGroup()
                                .addGroup(pnleditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                                    .addComponent(txtven))
                                .addGap(50, 50, 50)
                                .addGroup(pnleditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addGroup(pnleditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnleditLayout.createSequentialGroup()
                                .addGroup(pnleditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtp2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txttin, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtgst, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(46, 46, 46))
                            .addComponent(txtp1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        pnleditLayout.setVerticalGroup(
            pnleditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnleditLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnedit)
                .addGap(32, 32, 32)
                .addGroup(pnleditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtven, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnleditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnleditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)))
                .addGap(18, 18, 18)
                .addGroup(pnleditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtcity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnleditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)))
                .addGap(18, 18, 18)
                .addGroup(pnleditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtmn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txttin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnleditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtgst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtln, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(btnsave)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pnledit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 1170, 430));
        getContentPane().add(sep, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 1170, 10));

        jPanel2.setBackground(new java.awt.Color(214, 223, 245));

        cbcrit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbcritKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cbcritKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cbcritKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cbcrit, 0, 990, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cbcrit, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 990, 30));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nisarg1200.jpg"))); // NOI18N
        jLabel13.setMaximumSize(new java.awt.Dimension(1200, 500));
        jLabel13.setMinimumSize(new java.awt.Dimension(1200, 500));
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnemptyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnemptyActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblvendor.getModel();
        int rows = model.getRowCount();
        //Now remove all the rows from the current table model
        if (rows>0)
        {
            for(int i = 0; i<rows;i++)
            {
                model.removeRow(0);
            }
        }
    }//GEN-LAST:event_btnemptyActionPerformed

    private void btnsrchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsrchActionPerformed
        // TODO add your handling code here:
        btnempty.doClick();
        DefaultTableModel model = (DefaultTableModel) tblvendor.getModel();
        try
        {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/stockinventorymanagement","root","tabla10a");
            Statement stmt = con.createStatement();
            String sfld = (String) cbsrch.getSelectedItem();
            String crit,query;   
            crit = (String) cbcrit.getSelectedItem();
            query = "select * from vendormaster where "+sfld+" = '"+crit+"' ;";           
            ResultSet rs = stmt.executeQuery(query);
            for(int r = 1;rs.next();r++)
            {
                String ven= rs.getString("vendorname");
                String cat = rs.getString("address");
                String city = rs.getString("city");
                String mn = rs.getString("mobileno");
                String ln = rs.getString("landlineno");
                String p1 = rs.getString("person1");
                String p2 = rs.getString("person2");
                String email = rs.getString("email");
                String tin = rs.getString("tinno");
                String gst = rs.getString("gstno");
                model.addRow(new Object[] {r,ven,cat,city,mn,ln,p1,p2,email,tin,gst});
            }
            rs.close();
            stmt.close();
            con.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_btnsrchActionPerformed

    private void cbsrchItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbsrchItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbsrchItemStateChanged

    private void cbsrchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbsrchActionPerformed
        // TODO add your handling code here:
        String sfld = (String) cbsrch.getSelectedItem();
        if(sfld.equals("Select Field"))
        {        
            btnsrch.setEnabled(false);            
            DefaultTableModel model = (DefaultTableModel) tblvendor.getModel();
            while (model.getRowCount()>0)
            model.removeRow(0);
            cbcrit.removeAllItems();
            cbcrit.setVisible(false);
        }
        else if(sfld.equals("vendorName"))
        {
            btnsrch.setEnabled(true);                           
            cbcrit.setVisible(true);
            cbcrit.removeAllItems();
            try
            {
                Class.forName("java.sql.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost/stockinventorymanagement","root","tabla10a");
                Statement stmt = con.createStatement();
                String s = "select distinct VENDORName from vendormaster order by vendorname;";
                ResultSet rs = stmt.executeQuery(s);
                while(rs.next())
                {
                    String vendorName = rs.getString("vendorName");
                    cbcrit.addItem(vendorName);
                }
                rs.close();
                stmt.close();
                con.close();
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,e);
            }
        }
        else if(sfld.equals("address"))
        {
            btnsrch.setEnabled(true);                               
            cbcrit.setVisible(true);
            cbcrit.removeAllItems();
            try
            {
                Class.forName("java.sql.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost/stockinventorymanagement","root","tabla10a");
                Statement stmt = con.createStatement();
                String s = "select distinct address from vendormaster order by address;";
                ResultSet rs = stmt.executeQuery(s);
                while(rs.next())
                {
                    String add = rs.getString("address");
                    cbcrit.addItem(add);
                }
                rs.close();
                stmt.close();
                con.close();
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,e);
            }
        }
        else if(sfld.equals("city"))
        {
            btnsrch.setEnabled(true);              
            cbcrit.setVisible(true);
            cbcrit.removeAllItems();
            try
            {
                Class.forName("java.sql.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost/stockinventorymanagement","root","tabla10a");
                Statement stmt = con.createStatement();
                String query="SELECT DISTINCT CITY FROM vendorMASTER ORDER BY city;";
                ResultSet rs=stmt.executeQuery(query);
                while (rs.next())
                {
                    String city= rs.getString("city");
                    cbcrit.addItem(city);
                }
                rs.close();
                stmt.close();
                con.close();
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,e);
            }
        }
        else if(sfld.equals("mobileNo"))
        {
            btnsrch.setEnabled(true);                   
            cbcrit.setVisible(true);
            cbcrit.removeAllItems();
            try
            {
                Class.forName("java.sql.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost/stockinventorymanagement","root","tabla10a");
                Statement stmt = con.createStatement();
                String query="SELECT DISTINCT mobileno FROM vendorMASTER ORDER BY mobileno;";
                ResultSet rs=stmt.executeQuery(query);
                while (rs.next())
                {
                    String mn= rs.getString("mobileno");
                    cbcrit.addItem(mn);
                }
                rs.close();
                stmt.close();
                con.close();
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,e);
            }
        }
        else if(sfld.equals("landlineNo"))
        {
            btnsrch.setEnabled(true);                   
            cbcrit.setVisible(true);
            cbcrit.removeAllItems();
            try
            {
                Class.forName("java.sql.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost/stockinventorymanagement","root","tabla10a");
                Statement stmt = con.createStatement();
                String query="SELECT DISTINCT landlineno FROM vendorMASTER ORDER BY landlineno;";
                ResultSet rs=stmt.executeQuery(query);
                while (rs.next())
                {
                    String ln = rs.getString("landlineno");
                    cbcrit.addItem(ln);
                }
                rs.close();
                stmt.close();
                con.close();
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,e);
            }
        }
        else if(sfld.equals("person1"))
        {
            btnsrch.setEnabled(true);             
            cbcrit.setVisible(true);
            cbcrit.removeAllItems();
            try
            {
                Class.forName("java.sql.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost/stockinventorymanagement","root","tabla10a");
                Statement stmt = con.createStatement();
                String query="SELECT DISTINCT person1 FROM vendorMASTER ORDER BY person1;";
                ResultSet rs=stmt.executeQuery(query);
                while (rs.next())
                {
                    String p1 = rs.getString("person1");
                    cbcrit.addItem(p1);
                }
                rs.close();
                stmt.close();
                con.close();
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,e);
            }
        }
        else if(sfld.equals("person2"))
        {
            btnsrch.setEnabled(true);            
            cbcrit.setVisible(true);
            cbcrit.removeAllItems();
            try
            {
                Class.forName("java.sql.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost/stockinventorymanagement","root","tabla10a");
                Statement stmt = con.createStatement();
                String query="SELECT DISTINCT person2 FROM vendorMASTER ORDER BY person2;";
                ResultSet rs=stmt.executeQuery(query);
                while (rs.next())
                {
                    String p2= rs.getString("person2");
                    cbcrit.addItem(p2);
                }
                rs.close();
                stmt.close();
                con.close();
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,e);
            }
        }
        else if(sfld.equals("email"))
        {
            btnsrch.setEnabled(true);                 
            cbcrit.setVisible(true);
            cbcrit.removeAllItems();
            try
            {
                Class.forName("java.sql.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost/stockinventorymanagement","root","tabla10a");
                Statement stmt = con.createStatement();
                String query="SELECT DISTINCT email FROM vendorMASTER ORDER BY email;";
                ResultSet rs=stmt.executeQuery(query);
                while (rs.next())
                {
                    String email= rs.getString("email");
                    cbcrit.addItem(email);
                }
                rs.close();
                stmt.close();
                con.close();
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,e);
            }
        }
        else if(sfld.equals("tinNo"))
        {
            btnsrch.setEnabled(true);                  
            cbcrit.setVisible(true);
            cbcrit.removeAllItems();
            try
            {
                Class.forName("java.sql.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost/stockinventorymanagement","root","tabla10a");
                Statement stmt = con.createStatement();
                String query="SELECT DISTINCT tinNo FROM vendorMASTER ORDER BY tinNo;";
                ResultSet rs=stmt.executeQuery(query);
                while (rs.next())
                {
                    String tin= rs.getString("tinNo");
                    cbcrit.addItem(tin);
                }
                rs.close();
                stmt.close();
                con.close();
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,e);
            }
        }
        else if(sfld.equals("gstNo"))
        {
            btnsrch.setEnabled(true);                 
            cbcrit.setVisible(true);
            cbcrit.removeAllItems();
            try
            {
                Class.forName("java.sql.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost/stockinventorymanagement","root","tabla10a");
                Statement stmt = con.createStatement();
                String query="SELECT DISTINCT gstNo FROM vendorMASTER ORDER BY gstNo;";
                ResultSet rs=stmt.executeQuery(query);
                while (rs.next())
                {
                    String gst = rs.getString("gstNo");
                    cbcrit.addItem(gst);
                }
                rs.close();
                stmt.close();
                con.close();
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,e);
            }
        }        
    }//GEN-LAST:event_cbsrchActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        try
        {
            Class.forName("java.sql.Driver");   
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/stockinventorymanagement","root","tabla10a");
            Statement stmt = con.createStatement();
            String query = "select * from login";
            ResultSet rs = stmt.executeQuery(query);
            rs.next();
            String user = rs.getString("username");            
            if(user.equals("Admin"))
            {
                String q = "select*from access;";
                ResultSet rs1 = stmt.executeQuery(q);
                while(rs1.next())
                {
                    String f = rs1.getString("feature");                    
                    if(f.equals("edit"))
                    {
                        btnedit.setEnabled(true);
                        pnledit.setVisible(true);
                    }
                    else
                    {
                        
                        this.setSize(1200, 500);                        
                        pnledit.setVisible(false);
                        sep.setVisible(false);
                    }
                }
                rs1.close();
            }
            rs.close();
            stmt.close();
            con.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
        Color s=new Color(214,223,245);
        scrvendor.getViewport().setBackground(s);
        Color c= new Color(140,170,230);
        this.getContentPane().setBackground(c);
        txtven.setDisabledTextColor(Color.black);
        txtven.setBackground(Color.white);
        txtcity.setDisabledTextColor(Color.black);
        txtcity.setBackground(Color.white);
        txtmn.setDisabledTextColor(Color.black);
        txtmn.setBackground(Color.white);
        txtln.setDisabledTextColor(Color.black);
        txtln.setBackground(Color.white);
        txtp1.setDisabledTextColor(Color.black);
        txtp1.setBackground(Color.white);
        txtp2.setDisabledTextColor(Color.black);
        txtp2.setBackground(Color.white);
        txtemail.setDisabledTextColor(Color.black);
        txtemail.setBackground(Color.white);
        txtcity.setDisabledTextColor(Color.black);
        txtcity.setBackground(Color.white);
        txttin.setDisabledTextColor(Color.black);
        txttin.setBackground(Color.white);
        txtgst.setDisabledTextColor(Color.black);
        txtgst.setBackground(Color.white);
    }//GEN-LAST:event_formWindowOpened

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowActivated

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        String ven=txtven.getText();
        String add=txtadd.getText();
        String city=txtcity.getText();
        String mn=txtmn.getText();
        String ln=txtln.getText();
        String p1=txtp1.getText();
        String p2=txtp2.getText();
        String email=txtemail.getText();
        String tin=txttin.getText();
        String gst=txtgst.getText();
        if(city.equals("")||tin.equals("")||gst.equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please fill in the required fields!");
        }
        else
        {
            int x,c=0;
            int mnlength = mn.length();
            for(x=0;x<mnlength;x++)
            {
                char a = mn.charAt(x);
                if(a<=57&&a>=48)
                {
                    continue;
                }
                else
                {
                    c++;
                }
            }
            int lnlength = ln.length();
            for(x=0;x<lnlength;x++)
            {
                char a = ln.charAt(x);
                if(a<=57&&a>=48)
                {
                    continue;
                }
                else
                {
                    c++;
                }
            }
            if(c!=0)
            {
                JOptionPane.showMessageDialog(null,"Enter digits in Mobile Number and Landline Number!");
            }
            else
            {
                if(mn.equals(""))
                {
                    if(lnlength>10)
                    {
                        JOptionPane.showMessageDialog(null,"Landline Number must not exceed 10 digits!");
                    }
                    else
                    {
                        try
                        {
                            Class.forName("java.sql.Driver");
                            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/stockinventorymanagement","root","tabla10a");
                            Statement stmt = con.createStatement();
                            String update= "UPDATE vendormaster set address='"+add+"',city='"+city+"',mobileno='"+mn+"',landlineno='"+ln+"',person1='"+p1+"',person2='"+p2+"',email='"+email+"',tinno='"+tin+"',gstno='"+gst+"' where vendorname='"+ven+"';";
                            stmt.executeUpdate(update);
                            btnsrch.doClick();
                            JOptionPane.showMessageDialog(null,"Record Updated successfully.");
                            txtven.setText("");
                            txtadd.setText("");
                            txtcity.setText("");
                            txtmn.setText("");
                            txtln.setText("");
                            txtp1.setText("");
                            txtp2.setText("");
                            txtemail.setText("");
                            txttin.setText("");
                            txtgst.setText("");
                            btnsave.setEnabled(false);
                            txtven.setEnabled(false);
                            txtcity.setEnabled(false);
                            txtadd.setEnabled(false);
                            txtln.setEnabled(false);
                            txtmn.setEnabled(false);
                            txtemail.setEnabled(false);
                            txtp2.setEnabled(false);
                            txtp1.setEnabled(false);
                            txtgst.setEnabled(false);
                            txttin.setEnabled(false);
                            stmt.close();
                            con.close();
                        }
                        catch(Exception e)
                        {
                            JOptionPane.showMessageDialog(null,e);
                        }
                    }
                }
                else
                {
                    if(mn.length()!=10)
                    {
                        JOptionPane.showMessageDialog(null,"Mobile Number must be of 10 digits only!");
                    }
                    else if(ln.length()>10)
                    {
                        JOptionPane.showMessageDialog(null,"Landline Number must not exceed 10 digits!");
                    }
                    else
                    {
                        try
                        {
                            Class.forName("java.sql.Driver");
                            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/stockinventorymanagement","root","tabla10a");
                            Statement stmt = con.createStatement();
                            String insert = "UPDATE vendormaster set address='"+add+"',city='"+city+"',mobileno='"+mn+"',landlineno='"+ln+"',person1='"+p1+"',person2='"+p2+"',email='"+email+"',tinno='"+tin+"',gstno='"+gst+"' where vendorname='"+ven+"';";
                            stmt.executeUpdate(insert);
                            btnsrch.doClick();
                            JOptionPane.showMessageDialog(null,"Record Updated successfully.");
                            txtven.setText("");
                            txtadd.setText("");
                            txtcity.setText("");
                            txtmn.setText("");
                            txtln.setText("");
                            txtp1.setText("");
                            txtp2.setText("");
                            txtemail.setText("");
                            txttin.setText("");
                            txtgst.setText("");
                            btnsave.setEnabled(false);
                            txtven.setEnabled(false);
                            txtcity.setEnabled(false);
                            txtadd.setEnabled(false);
                            txtln.setEnabled(false);
                            txtmn.setEnabled(false);
                            txtemail.setEnabled(false);
                            txtp2.setEnabled(false);
                            txtp1.setEnabled(false);
                            txtgst.setEnabled(false);
                            txttin.setEnabled(false);
                            stmt.close();
                            con.close();
                        }
                        catch(Exception e)
                        {
                            JOptionPane.showMessageDialog(null,e);
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:
        if(tblvendor.getSelectionModel().isSelectionEmpty())
        {
            JOptionPane.showMessageDialog(null,"Please select a row from the Table to Edit.");
        }
        else
        {
            btnsave.setEnabled(true);
            txtcity.setEnabled(true);
            txtadd.setEnabled(true);
            txtln.setEnabled(true);
            txtmn.setEnabled(true);
            txtemail.setEnabled(true);
            txtp2.setEnabled(true);
            txtp1.setEnabled(true);
            txtgst.setEnabled(true);
            txttin.setEnabled(true);
            DefaultTableModel model=(DefaultTableModel) tblvendor.getModel();
            int i = tblvendor.getSelectedRow();
            txtven.setText(model.getValueAt(i,1).toString());
            txtadd.setText(model.getValueAt(i,2).toString());
            txtcity.setText(model.getValueAt(i,3).toString());
            txtmn.setText(model.getValueAt(i,4).toString());
            txtln.setText(model.getValueAt(i,5).toString());
            txtp1.setText(model.getValueAt(i,6).toString());
            txtp2.setText(model.getValueAt(i,7).toString());
            txtemail.setText(model.getValueAt(i,8).toString());
            txttin.setText(model.getValueAt(i,9).toString());
            txtgst.setText(model.getValueAt(i,10).toString());
        }
    }//GEN-LAST:event_btneditActionPerformed

    private void cbcritKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbcritKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_cbcritKeyTyped

    private void cbcritKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbcritKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_cbcritKeyReleased

    private void cbcritKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbcritKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbcritKeyPressed

    private void txtvenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(exploreVendor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(exploreVendor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(exploreVendor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(exploreVendor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new exploreVendor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnempty;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnsrch;
    private javax.swing.JComboBox<String> cbcrit;
    private javax.swing.JComboBox<String> cbsrch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel pnledit;
    private javax.swing.JScrollPane scrvendor;
    private javax.swing.JSeparator sep;
    private javax.swing.JTable tblvendor;
    private javax.swing.JTextArea txtadd;
    private javax.swing.JTextField txtcity;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtgst;
    private javax.swing.JTextField txtln;
    private javax.swing.JTextField txtmn;
    private javax.swing.JTextField txtp1;
    private javax.swing.JTextField txtp2;
    private javax.swing.JTextField txttin;
    private javax.swing.JTextField txtven;
    // End of variables declaration//GEN-END:variables

}
