/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stockinventorymanagement;
import javax.swing.JOptionPane;
import java.sql.*;
import java.text.SimpleDateFormat;
import com.toedter.calendar.JTextFieldDateEditor;
import java.awt.Color;
import javax.swing.ImageIcon;
import java.util.Date;
/**
 *
 * @author Anish
 */
public class stockEntry extends javax.swing.JFrame {

    /**
     * Creates new form stockEntry
     */
    public stockEntry() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/images/logo.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioButton2 = new javax.swing.JRadioButton();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtbatch = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtoq = new javax.swing.JTextField();
        chexp = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnsave = new javax.swing.JButton();
        cal = new com.toedter.calendar.JDateChooser();
        cbitem = new javax.swing.JComboBox<>();
        btncancel = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        jRadioButton2.setText("jRadioButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Stock Entry");
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowIconified(java.awt.event.WindowEvent evt) {
                formWindowIconified(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(62, 53, 171));
        jLabel2.setText("Item Name :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(62, 53, 171));
        jLabel3.setText("Batch No. :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 100, 20));

        txtbatch.setEnabled(false);
        getContentPane().add(txtbatch, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 150, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(62, 53, 171));
        jLabel4.setText("Opening Qty. :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        txtoq.setEnabled(false);
        txtoq.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtoqFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtoqFocusLost(evt);
            }
        });
        txtoq.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtoqKeyTyped(evt);
            }
        });
        getContentPane().add(txtoq, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 150, -1));

        chexp.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        chexp.setForeground(new java.awt.Color(62, 53, 171));
        chexp.setText("Expiry Date:");
        chexp.setEnabled(false);
        chexp.setOpaque(false);
        chexp.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chexpItemStateChanged(evt);
            }
        });
        getContentPane().add(chexp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 51, 0));
        jLabel8.setText("* = Required Fields");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, 20));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 51, 0));
        jLabel9.setText("*");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, 14, 23));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 51, 0));
        jLabel12.setText("*");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 21, 39));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 51, 0));
        jLabel13.setText("*");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 21, 26));

        btnsave.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnsave.setText(" Save ");
        btnsave.setEnabled(false);
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 150, -1));

        cal.setEnabled(false);
        getContentPane().add(cal, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 170, -1));

        cbitem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select an Item" }));
        cbitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbitemActionPerformed(evt);
            }
        });
        getContentPane().add(cbitem, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 400, -1));

        btncancel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btncancel.setText("Cancel");
        btncancel.setEnabled(false);
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });
        getContentPane().add(btncancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, 150, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nisarg600.jpeg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        txtbatch.setDisabledTextColor(Color.black);
        txtbatch.setBackground(Color.white);
        txtoq.setDisabledTextColor(Color.black);
        txtoq.setBackground(Color.white);
        JTextFieldDateEditor editor = (JTextFieldDateEditor) cal.getDateEditor();            
        editor.setBackground(Color.white);
        editor.setDisabledTextColor(Color.black);
    }//GEN-LAST:event_formWindowActivated

    private void chexpItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chexpItemStateChanged
        // TODO add your handling code here:
        if(chexp.isSelected()==true)
        {
            cal.setEnabled(true);
            JTextFieldDateEditor editor = (JTextFieldDateEditor) cal.getDateEditor();
            editor.setEnabled(false);
            editor.setBackground(Color.white);
            editor.setDisabledTextColor(Color.black);
        }
        if(chexp.isSelected()==false)
        {
            cal.setEnabled(false);
            JTextFieldDateEditor editor = (JTextFieldDateEditor) cal.getDateEditor();            
            editor.setBackground(Color.white);
            editor.setDisabledTextColor(Color.black);
            cal.setCalendar(null);
        }
    }//GEN-LAST:event_chexpItemStateChanged

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        String item, batch, exp, oqs;
        int oq;
        item = cbitem.getSelectedItem().toString();
        batch = txtbatch.getText();
        oqs = txtoq.getText();
        int temp=0;
        if(item.equals("")||batch.equals("")||oqs.equals(""))
        {
            JOptionPane.showMessageDialog(null,"Fill in the required fields!");
        }
        else
        {
            int oqslength = oqs.length();
            int x,c=0;
            for(x=0;x<oqslength;x++)
            {
                char a = oqs.charAt(x);
                if(a<=57&&a>=48)
                {
                    continue;
                }
                else
                {
                    c++;
                }
            }
            if(c!=0)
            {
                JOptionPane.showMessageDialog(null,"Enter numbers in opening quantity!");
            }
            else
            {
                try
                {
                    Class.forName("java.sql.Driver");
                    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/stockinventorymanagement","root","tabla10a");
                    Statement stm = conn.createStatement();
                    String query = "SELECT BATCHNO FROM STOCKMASTER WHERE ITEMNAME ='"+item+"';";
                    ResultSet rs =stm.executeQuery(query);
                    while(rs.next())
                    {
                        String batchno=rs.getString("batchno");
                        if(batchno.equals(batch))
                        {
                            temp=1;
                        }
                    }
                    rs.close();
                    stm.close();
                    conn.close();
                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null,e);
                }
                if(temp==1)
                {
                    JOptionPane.showMessageDialog(null,"Repetition of batch no. is not allowed! Try again.");
                }
                else
                {
                    oq = Integer.parseInt(oqs);
                    if (chexp.isSelected()==false)
                    {
                        exp="-";
                        try
                        {
                            Class.forName("java.sql.Driver");
                            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/stockinventorymanagement","root","tabla10a");
                            Statement stm = conn.createStatement();
                            String str = "INSERT INTO stockMaster values('"+item+"','"+batch+"','"+oqs+"','"+exp+"');";
                            stm.executeUpdate(str);
                            JOptionPane.showMessageDialog(null,"Record Saved successfully.");
                            txtbatch.setText("");
                            txtoq.setText("");
                            chexp.setSelected(false);
                            stm.close();
                            conn.close();
                        }
                        catch(Exception e)
                        {
                            JOptionPane.showMessageDialog(null,e);   
                        }
                    }
                    else
                    {
                        if(cal.getCalendar()==null)
                        {
                            JOptionPane.showMessageDialog(null,"Select an Expiry Date!");
                        }
                        else
                        {
                            SimpleDateFormat df = new SimpleDateFormat("d MMM, yyyy");
                            exp = df.format(cal.getDate());
                            String date = exp.substring(0,2);
                            String d,month,year;
                            if(date.substring(1,2).equals(" "))
                            {
                                d = "0"+date.substring(0,1);
                                month = exp.substring(2,5);
                                year = exp.substring(7,11);
                            }
                            else
                            {
                                d = date;
                                month = exp.substring(3,6);
                                year = exp.substring(8,12);
                            }
                            String mon="";
                            if(month.equals("Jan"))
                            {
                                mon="01";
                            }
                            else if(month.equals("Feb"))
                            {
                                mon="02";
                            }
                            else if(month.equals("Mar"))
                            {
                                mon="03";
                            }
                            else if(month.equals("Apr"))
                            {
                                mon="04";
                            }
                            else if(month.equals("May"))
                            {
                                mon="05";
                            }
                            else if(month.equals("Jun"))
                            {
                                mon="06";
                            }
                            else if(month.equals("Jul"))
                            {
                                mon="07";
                            }
                            else if(month.equals("Aug"))
                            {
                                mon="08";
                            }
                            else if(month.equals("Sep"))
                            {
                                mon="09";
                            }
                            else if(month.equals("Oct"))
                            {
                                mon="10";
                            }
                            else if(month.equals("Nov"))
                            {
                                mon="11";
                            }
                            else if(month.equals("Dec"))
                            {
                                mon="12";
                            }
                            int y = Integer.parseInt(year);
                            String curdate = java.time.LocalDate.now().toString();
                            String curmonth = curdate.substring(5,7);
                            String curyear = curdate.substring(0,4);
                            int curm = Integer.parseInt(curmonth);
                            int cury = Integer.parseInt(curyear);
                            int m = Integer.parseInt(mon);
                            exp = year+"-"+mon+"-"+d;
                            if(y>cury)
                            {
                                try
                                {
                                    Class.forName("java.sql.Driver");
                                    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/stockinventorymanagement","root","tabla10a");
                                    Statement stm = conn.createStatement();
                                    String str = "INSERT INTO stockMaster values('"+item+"','"+batch+"','"+oqs+"','"+exp+"');";
                                    stm.executeUpdate(str);
                                    JOptionPane.showMessageDialog(null,"Record Saved successfully.");
                                    txtbatch.setText("");
                                    txtoq.setText("");
                                    chexp.setSelected(false);
                                    stm.close();
                                    conn.close();
                                }
                                catch(Exception e)
                                {
                                    JOptionPane.showMessageDialog(null,e);   
                                }
                            }
                            else if(y==cury)
                            {
                                if(m>curm)
                                {
                                    try
                                    {
                                        Class.forName("java.sql.Driver");
                                        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/stockinventorymanagement","root","tabla10a");
                                        Statement stm = conn.createStatement();
                                        String str = "INSERT INTO stockMaster values('"+item+"','"+batch+"','"+oqs+"','"+exp+"');";
                                        stm.executeUpdate(str);
                                        JOptionPane.showMessageDialog(null,"Record Saved successfully.");
                                        txtbatch.setText("");
                                        txtoq.setText("");
                                        chexp.setSelected(false);
                                        stm.close();
                                        conn.close();
                                    }
                                    catch(Exception e)
                                    {
                                        JOptionPane.showMessageDialog(null,e);   
                                    }
                                }
                                else
                                {
                                    JOptionPane.showMessageDialog(null,"Invalid Expiry Date. Try again.");
                                }
                            }
                            else
                            {
                                JOptionPane.showMessageDialog(null,"Invalid Expiry Date. Try again.");
                            }
                        }
                    }
                }
            }
        }                            
    }//GEN-LAST:event_btnsaveActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        cal.setMinSelectableDate(new Date());
        Color c= new Color(140,170,230);
        this.getContentPane().setBackground(c);
        try
        {
             Class.forName("java.sql.Driver");
             Connection con = DriverManager.getConnection("jdbc:mysql://localhost/stockinventorymanagement","root","tabla10a");
             Statement stmt = con.createStatement();
             String query = "SELECT itemName from itemMaster;";
             ResultSet rs = stmt.executeQuery(query);
             while(rs.next()){
                 String in = rs.getString(1);
                 cbitem.addItem(in);
             }
             rs.next();
             stmt.close();
             con.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_formWindowOpened

    private void txtoqKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtoqKeyTyped
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_txtoqKeyTyped

    private void txtoqFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtoqFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtoqFocusGained

    private void txtoqFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtoqFocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtoqFocusLost

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowClosed

    private void cbitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbitemActionPerformed
        // TODO add your handling code here:
        if(cbitem.getSelectedIndex()==0)
        {
            txtbatch.setEnabled(false);
            txtbatch.setText("");
            txtoq.setEnabled(false);
            txtoq.setText("");
            chexp.setEnabled(false);
            chexp.setSelected(false);
            btnsave.setEnabled(false);
            btncancel.setEnabled(false);
        }
        else
        {
            txtbatch.setEnabled(true);
            txtbatch.setText("");
            txtoq.setEnabled(true);
            txtoq.setText("");
            chexp.setEnabled(true);
            btnsave.setEnabled(true);
            btncancel.setEnabled(true);
        }
    }//GEN-LAST:event_cbitemActionPerformed

    private void formWindowIconified(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowIconified
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowIconified

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        // TODO add your handling code here:
        cbitem.setSelectedIndex(0);
        txtbatch.setText("");
        txtoq.setText("");
        chexp.setSelected(false);
    }//GEN-LAST:event_btncancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(stockEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(stockEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(stockEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(stockEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new stockEntry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btnsave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private com.toedter.calendar.JDateChooser cal;
    private javax.swing.JComboBox<String> cbitem;
    private javax.swing.JCheckBox chexp;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField txtbatch;
    private javax.swing.JTextField txtoq;
    // End of variables declaration//GEN-END:variables
}
